### ISSUE TITLE
Embed the source code of shaders in the executables

### ISSUE THREAD

**Issue by rlepigre** [craff/gles3#2]
Currently the examples must be run in the same directory as that containing the source code of the required shaders. It would be nice to provide a way to embed this source code in the exectuable so that it can be run from anywhere.

One solution would be to rely on something like https://github.com/johnwhitington/ppx_blob.

**Comment by craff** [comment]
The simplest is to create a ml file from a .glsl file, holding just one string.
I am looking how a general rule can be created with dune

**Comment by rlepigre** [comment]
Yes, you are right. I don't think we can define a general rule, in the sense that it will need to be repeated for every glsl file.
However, what you propose can be achieved with `(rule ...)` and it is probably a good first solution. I can take care of it tomorrow if you want, and if you have not already done it by then!

**Comment by craff** [comment]
Je viens de pusher une branche ml from glsl with a build rule in dune to transform 
file.glsl into file.ml containing let str = "glsl source code"

Problem; I do not know how to write this rule to have it for any .glsl file, even for user using the library ? Can an opam package extend automatically dune with new rules when it is used ?

May be we can just tell ocaml that glsl file are juste ml file that needs a preprocessor.

**Comment by rlepigre** [comment]
Yeah, you cannot currently do that with dune. We might be able to do something with a trivial preprocessor, however this will not solve the issue that some dune stanzas will be needed for every glsl file.

However, we can always use the approach I mentioned in the issue. This allows you to include the contents of a file as an OCaml string using `[%blob "path/to/the/file.glsl"]`, which is not too bad.

**Comment by craff** [comment]
Coucou,

I did a new branch ml_from_glsl with a rule to build examples/curves. It works.

I really would prefer a rule with joker like %.ml: %.glsl from make.

Could not find a way to do this for dune ... So we could have one rule
per glsl ...

We can also put all glsl in the same ml file ...

A plus,
Christophe

**Comment by rlepigre** [comment]
I pushed a version with a shorter rule to your branch (using a tool program).
Feel free to revert if you don't like it, I only used it in one example so that you can see what it looks like.
(I'm way past my bedtime, so I won't touch anything before tomorrow...)

A+
Rodolphe.

**Comment by craff** [comment]
We work together ... I did all the remaining example ... I look you stuff

**Comment by craff** [comment]
I don't have your shorter rule ? did you push ?

**Comment by craff** [comment]
Sinon on peut effectivement dépendre de ppx_blob ?

**Comment by craff** [comment]
C'est non je l'ai ...

**Comment by craff** [comment]
I am ok with current ... I do a PR, you can check ...

**Comment by rlepigre** [comment]
Fixed by f136cd195d9baa31e4fdb6c7094a6e32c8a212e4.

**Comment by rlepigre** [comment]
> We work together ... I did all the remaining example ... I look you stuff

Sorry, I thought you would see this straight away.
